version: '2'
services:
  activiti-cloud-connectors-twitter:
      image: blueprint/activiti-cloud-connectors-dummytwitter
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
#        - TWITTER4J_OAUTH_CONSUMERKEY=<TWITTER4J_OAUTH_CONSUMERKEY> #for live twitter get credentials replacing placeholders by signing up at apps.twitter.com
#        - TWITTER4J_OAUTH_CONSUMERSECRET=<TWITTER4J_OAUTH_CONSUMERSECRET>
#        - TWITTER4J_OAUTH_ACCESSTOKEN=<TWITTER4J_OAUTH_ACCESSTOKEN>
#        - TWITTER4J_OAUTH_ACCESSTOKENSECRET=<TWITTER4J_OAUTH_ACCESSTOKENSECRET>
        - JAVA_OPTS=-Xmx64m -Xms64m
        - tweet_rate=50
      ports:
        - "8082:8082"
      external_links:
        - rabbitmq
      networks:
        - infrastructure
  activiti-cloud-connectors-ranking:
      image: blueprint/activiti-cloud-connectors-ranking
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
        - JAVA_OPTS=-Xmx64m -Xms64m
      ports:
        - "8083:8083"
      external_links:
        - rabbitmq
      networks:
        - infrastructure
  activiti-cloud-connectors-processing:
      image: blueprint/activiti-cloud-connectors-processing
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
        - JAVA_OPTS=-Xmx256m -Xms256m
      external_links:
        - rabbitmq
      networks:
        - infrastructure
  activiti-cloud-connectors-reward:
      image: blueprint/activiti-cloud-connectors-reward
      ports:
        - "8085:8085"
      environment:
        - ACT_RABBITMQ_HOST=rabbitmq
        - JAVA_OPTS=-Xmx64m -Xms64m
        - campaignCycle1_campaigns=activiti-en,alfresco-en
      external_links:
        - rabbitmq
      networks:
        - infrastructure
# we will join the infrastructure network defined by the infrastructure docker compose.
networks:
  infrastructure:
    external:
      name: docker_default
