apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-connectors-processing
  labels:
    app: infrastructure
    serviceType: connector-processing
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-connectors-processing
      labels:
        app: infrastructure
        serviceType: connector-processing
    spec:
      containers:
        - name: activiti-cloud-connectors-processing
          image: activiti/activiti-cloud-connectors-processing:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
          - name: SERVER_PORT
            value: "8084"
          - name: ACT_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_APPLICATION_NAME
            value: "activiti-cloud-connectors-processing"
          - name: JAVA_OPTS
            value: -Xmx256m -Xms256m
          - name: SPRING_PROFILES_ACTIVE
            value: kube,local
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-connectors-processing
  namespace: default
spec:
  selector:
    serviceType: connector-processing
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-connectors-ranking
  labels:
    app: infrastructure
    serviceType: connector-ranking
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-connectors-ranking
      labels:
        app: infrastructure
        serviceType: connector-ranking
    spec:
      containers:
        - name: activiti-cloud-connectors-ranking
          image: activiti/activiti-cloud-connectors-ranking:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
          - name: SERVER_PORT
            value: "8083"
          - name: ACT_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_APPLICATION_NAME
            value: "activiti-cloud-connectors-ranking"
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_PROFILES_ACTIVE
            value: kube,local
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-connectors-ranking
  namespace: default
spec:
  selector:
    serviceType: connector-ranking
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-connectors-twitter
  labels:
    app: infrastructure
    serviceType: connector-twitter
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-connectors-twitter
      labels:
        app: infrastructure
        serviceType: connector-twitter
    spec:
      containers:
        - name: activiti-cloud-connectors-twitter
          image: activiti/activiti-cloud-connectors-dummytwitter:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
          - name: SERVER_PORT
            value: "8082"
          - name: ACT_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_APPLICATION_NAME
            value: "activiti-cloud-connectors-twitter"
#          - name: TWITTER4J_OAUTH_CONSUMERKEY #get credentials replacing placeholders by signing up at apps.twitter.com
#            value: <TWITTER4J_OAUTH_CONSUMERKEY>
#          - name: TWITTER4J_OAUTH_CONSUMERSECRET
#            value: <TWITTER4J_OAUTH_CONSUMERSECRET>
#          - name: TWITTER4J_OAUTH_ACCESSTOKEN
#            value: <TWITTER4J_OAUTH_ACCESSTOKEN>
#          - name: TWITTER4J_OAUTH_ACCESSTOKENSECRET
#            value: <TWITTER4J_OAUTH_ACCESSTOKENSECRET>
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_PROFILES_ACTIVE
            value: kube,local
          - name: tweet_rate
            value: "350"
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-connectors-twitter
  namespace: default
spec:
  selector:
    serviceType: connector-twitter
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-connectors-reward
  labels:
    app: infrastructure
    serviceType: connector-reward
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-connectors-reward
      labels:
        app: infrastructure
        serviceType: connector-reward
    spec:
      containers:
        - name: activiti-cloud-connectors-reward
          image: activiti/activiti-cloud-connectors-reward:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 130
            timeoutSeconds: 3
            periodSeconds: 40
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
          - name: SERVER_PORT
            value: "8085"
          - name: ACT_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_APPLICATION_NAME
            value: "activiti-cloud-connectors-reward"
          - name: campaignCycle1_campaigns
            value: "activiti-en"
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_PROFILES_ACTIVE
            value: kube,local
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-connectors-reward
  namespace: default
spec:
  selector:
    serviceType: connector-reward
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
---